### PR TITLE
Fix live workflow and add tests

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Requires scipp/essreduce#115 for CI to pass.

### CODE REVIEW

**Comment by YooSunYoung** [comment]
There is a typo here: 
https://github.com/scipp/esssans/blob/b0bd383156468dee1b0ba5a1da1d169081d403e8/pyproject.toml#L59-L60

The workflow class name should be ``LoKi`` not ``Loki``.

**Comment by SimonHeybrock** [comment]
> There is a typo here:
> 
> https://github.com/scipp/esssans/blob/b0bd383156468dee1b0ba5a1da1d169081d403e8/pyproject.toml#L59-L60
> 
> The workflow class name should be `LoKi` not `Loki`.

I don't think we are camelcasing Loki anywhere in this package?

**Comment by YooSunYoung** [comment]
The test is failing just because the new ``essreduce`` implementation is not released right?
When I tested it with https://github.com/scipp/beamlime/pull/242, it was complaining like this: 

```
AttributeError: 'JSONGroup' object has no attribute 'get'
```

<details>
<summary>
Full Error Message
</summary>
Traceback (most recent call last):
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/bin/beamlime", line 8, in <module>
    sys.exit(main())
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/__main__.py", line 18, in main
    run_standalone_prototype(factory, arg_name_space=arg_parser.parse_args())
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/executables/prototypes.py", line 113, in run_standalone_prototype
    app.run()
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/applications/base.py", line 277, in run
    loop.run_until_complete(asyncio.gather(*self.tasks))
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/applications/base.py", line 241, in run_daemon
    async for message in daemon.run():
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/applications/base.py", line 150, in run
    await self.route(self.message_pipe.get())
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/applications/base.py", line 124, in route
    results.extend(self._collect_results(handler(message)))
  File "/Users/sunyoungyoo/ESS/beamlime/src/beamlime/applications/handlers.py", line 175, in reduce_data
    results = self.workflow(nxevent_data=nxevent_data, nxlog=nxlog)
  File "/Users/sunyoungyoo/ESS/esssans/src/ess/loki/live.py", line 120, in __call__
    results = self._streamed.add_chunk({JSONEventData: nxevent_data})
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/ess/reduce/streaming.py", line 208, in add_chunk
    return self._finalize_workflow.compute(self._target_keys)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/sciline/pipeline.py", line 90, in compute
    return self.get(tp, **kwargs).compute()
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/sciline/task_graph.py", line 110, in compute
    results = self._scheduler.get(self._graph, list(targets))
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/sciline/scheduler.py", line 105, in get
    return self._dask_get(dsk, list(map(_to_dask_key, keys)))
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/threaded.py", line 91, in get
    results = get_async(
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/local.py", line 513, in get_async
    raise_exception(exc, tb)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/local.py", line 321, in reraise
    raise exc
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/local.py", line 226, in execute_task
    result = _execute_task(task, data)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/dask/utils.py", line 80, in apply
    return func(*args)
  File "/Users/sunyoungyoo/ESS/esssans/src/ess/loki/live.py", line 56, in load_json_transmission_monitor_data
    return nexus_types.NeXusMonitorData[SampleRun, Incident](group[()])
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/base.py", line 399, in __getitem__
    dg = self._nexus.read_children(sel)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/base.py", line 298, in _nexus
    self._populate_fields()
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/base.py", line 313, in _populate_fields
    self._lazy_nexus = self._definitions.get(self.attrs.get('NX_class'), NXobject)(
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/_cache.py", line 51, in __get__
    val = self.func(instance)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/base.py", line 233, in attrs
    return MappingProxyType(Attrs(self._group.attrs))
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/scippnexus/attrs.py", line 13, in __init__
    self._attrs = dict(attrs)
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/_collections_abc.py", line 886, in __iter__
    yield from self._mapping
  File "/Users/sunyoungyoo/miniconda3/envs/lime-dev-310/lib/python3.10/site-packages/ess/reduce/nexus/json_nexus.py", line 221, in __iter__
    if (attrs := self._node.get('attributes')) is not None:
AttributeError: 'JSONGroup' object has no attribute 'get'
</details>

**Comment by SimonHeybrock** [comment]
Sounds like there was as nested creation of `JSONGroup` ("constructing" it twice rather than once) in Beamlime? I will look into it.

**Pull request merged**
